// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"student/internal/dao/internal"
)

// internalInformationDao is internal type for wrapping internal DAO implements.
type internalInformationDao = *internal.InformationDao

// informationDao is the data access object for table information.
// You can define custom methods on it to extend its functionality as you wish.
type informationDao struct {
	internalInformationDao
}

var (
	// Information is globally public accessible object for table information operations.
	Information = informationDao{
		internal.NewInformationDao(),
	}
)

// Fill with you ideas below.
